export const inventoryList = [
  { name: 'Refrigerator' },
  { name: 'Oven' },
  { name: 'Sofa' },
  { name: 'Coffee Table' },
  { name: 'Table' },
  { name: 'Chair' },
  { name: 'Bed' },
  { name: 'Nightstand' },
  { name: 'Dresser' },
  { name: 'Desk' },
  { name: 'Desk Chair' },
  { name: 'Bookshelf' },
  { name: 'TV' },
  { name: 'TV Stand' },
  { name: 'Lamp' },
  { name: 'Microwave' },
  { name: 'Toaster' },
  { name: 'Blender' },
  { name: 'Pots' },
  { name: 'Dishes' },
  { name: 'Cups' },
  { name: 'Silverware' },
  { name: 'Towels' },
  { name: 'Sheets' },
  { name: 'Pillows' },
  { name: 'Blankets' },
  { name: 'Curtains' },
]
